version: "3"

services:
  flask_app:
    build: .
    ports:
      - "8000:5000"
    environment:
      - ENV_1=one
      - ENV_2=two
      - ENV_3=three
      - ENV_4=four
  
  interactive_ubuntu:
    image: ubuntu:latest
    tty: true
    
